DROP TABLE APP.FORECAST_CATEGORIES;

CREATE TABLE APP.FORECAST_CATEGORIES (
  ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  NAME varchar(100) NOT NULL,
  CONSTRAINT FORECAST_CATEGORIES_PK PRIMARY KEY (ID)
);