package org.mgnl.nicki.consulting.views;

import java.util.Map;

import org.mgnl.nicki.consulting.core.helper.TimeHelper;
import org.mgnl.nicki.consulting.data.BeanContainerDataSource;
import org.mgnl.nicki.consulting.db.OpenProject;
import org.mgnl.nicki.vaadin.base.menu.application.ConfigurableView;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class ClosingView extends BaseView implements ConfigurableView  {
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Button closingButton;
	@AutoGenerated
	private Button previewInvoiceButton;
	@AutoGenerated
	private Table projectsTable;

	private static final long serialVersionUID = -2330776406366438437L;
	private static final Logger LOG = LoggerFactory.getLogger(ClosingView.class);

	public static final String PROPERTY_BASE_DN = "nicki.templates.basedn";
	
	private boolean isInit;
	
	private BeanContainerDataSource<OpenProject> projectsContainerDataSource;
	private Map<String, String> configuration;
	private Window performClosingWindow;
	
	public ClosingView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

	}


	@Override
	public void init() {
		if (!isInit) {
			
			projectsContainerDataSource = new BeanContainerDataSource<>(OpenProject.class);
			projectsTable.setContainerDataSource(projectsContainerDataSource);
			projectsTable.setVisibleColumns("customerName", "projectName", "hours", "days", "since");
			projectsTable.setColumnHeaders("Kunde", "Projekt", "Stunden", "Tage", "offene Bunchungen seit");
			projectsTable.setSelectable(true);
			
			previewInvoiceButton.setEnabled(false);
			closingButton.setEnabled(false);
			
			projectsTable.addValueChangeListener(event -> projectSelected());
			previewInvoiceButton.addClickListener(event -> previewInvoice());
			closingButton.addClickListener(event -> performClosing());
			isInit = true;
		}
		loadProjects();
	}

	private void performClosing() {
		showPerformClosingWindow(true);
	}


	private void showPerformClosingWindow(boolean close) {
		OpenProject openProject = (OpenProject) projectsTable.getValue();
		PerformClosingView performClosingView = new PerformClosingView(this, openProject.getProject(), close);
		performClosingWindow = new Window(close? "Abschluss" : "Vorschau", performClosingView);
		performClosingWindow.setModal(true);
		UI.getCurrent().addWindow(performClosingWindow);
	}
	
	public void finshClosing() {
		if (performClosingWindow != null) {
			UI.getCurrent().removeWindow(performClosingWindow);
		}
		loadProjects();
	}


	private void previewInvoice() {
		showPerformClosingWindow(false);
	}


	private void projectSelected() {
		if (projectsTable.getValue() != null) {
			previewInvoiceButton.setEnabled(true);
			closingButton.setEnabled(true);
		} else {
			previewInvoiceButton.setEnabled(false);
			closingButton.setEnabled(false);
		}
	}


	private void loadProjects() {
		projectsContainerDataSource.removeAllItems();
		projectsContainerDataSource.addAll(TimeHelper.getOpenProjects(null));
	}


	public Map<String, String> getConfiguration() {
		return configuration;
	}


	public void setConfiguration(Map<String, String> configuration) {
		this.configuration = configuration;
	}
	
	


	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		return mainLayout;
	}


	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// projectsTable
		projectsTable = new Table();
		projectsTable.setImmediate(true);
		projectsTable.setWidth("-1px");
		projectsTable.setHeight("100.0%");
		horizontalLayout_1.addComponent(projectsTable);
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		horizontalLayout_1.addComponent(verticalLayout_2);
		
		return horizontalLayout_1;
	}


	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("-1px");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(true);
		verticalLayout_2.setSpacing(true);
		
		// previewInvoiceButton
		previewInvoiceButton = new Button();
		previewInvoiceButton.setCaption("Vorschau Rechnung");
		previewInvoiceButton.setImmediate(false);
		previewInvoiceButton.setWidth("200px");
		previewInvoiceButton.setHeight("-1px");
		verticalLayout_2.addComponent(previewInvoiceButton);
		
		// closingButton
		closingButton = new Button();
		closingButton.setCaption("Monatsabschluss");
		closingButton.setImmediate(false);
		closingButton.setWidth("200px");
		closingButton.setHeight("-1px");
		verticalLayout_2.addComponent(closingButton);
		
		return verticalLayout_2;
	}

}
