package org.mgnl.nicki.consulting.views;

import java.util.Map;
import java.util.Optional;
import java.util.Set;

import org.mgnl.nicki.consulting.core.helper.TimeHelper;
import org.mgnl.nicki.consulting.db.OpenProject;
import org.mgnl.nicki.vaadin.base.helper.UIHelper;
import org.mgnl.nicki.vaadin.base.menu.application.ConfigurableView;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.provider.ListDataProvider;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class ClosingView extends BaseView implements ConfigurableView  {
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Button closingButton;
	@AutoGenerated
	private Button previewInvoiceButton;
	@AutoGenerated
	private Grid<OpenProject> projectsTable;

	private static final long serialVersionUID = -2330776406366438437L;

	public static final String PROPERTY_BASE_DN = "nicki.templates.basedn";
	
	private boolean isInit;
	
	private Map<String, String> configuration;
	private Window performClosingWindow;
	
	public ClosingView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

	}


	@Override
	public void init() {
		if (!isInit) {
			
			projectsTable.addColumn(OpenProject::getCustomerName).setCaption("Kunde");
			projectsTable.addColumn(OpenProject::getProjectName).setCaption("Projekt");
			projectsTable.addColumn(OpenProject::getHours).setCaption("Stunden");
			projectsTable.addColumn(OpenProject::getDays).setCaption("Tage");
			projectsTable.addColumn(OpenProject::getSince).setCaption("offene Bunchungen seit");
			projectsTable.asSingleSelect();
			
			previewInvoiceButton.setEnabled(false);
			closingButton.setEnabled(false);
			
			projectsTable.addSelectionListener(event -> projectSelected(event.getFirstSelectedItem()));
			previewInvoiceButton.addClickListener(event -> previewInvoice());
			closingButton.addClickListener(event -> performClosing());
			isInit = true;
		}
		loadProjects();
	}

	private void performClosing() {
		showPerformClosingWindow(true);
	}


	private void showPerformClosingWindow(boolean close) {
		Set<OpenProject> openProjects = projectsTable.getSelectedItems();
		if (openProjects != null && openProjects.size() > 0) {
			OpenProject openProject = openProjects.iterator().next();
			PerformClosingView performClosingView = new PerformClosingView(this, openProject.getProject(), close);
			performClosingWindow = new Window(close? "Abschluss" : "Vorschau", performClosingView);
			performClosingWindow.setModal(true);
			UI.getCurrent().addWindow(performClosingWindow);
		}
	}
	
	public void finshClosing() {
		if (performClosingWindow != null) {
			UI.getCurrent().removeWindow(performClosingWindow);
		}
		loadProjects();
	}


	private void previewInvoice() {
		showPerformClosingWindow(false);
	}


	private void projectSelected(Optional<OpenProject> selectedItem) {
		if (selectedItem != null) {
			previewInvoiceButton.setEnabled(true);
			closingButton.setEnabled(true);
		} else {
			previewInvoiceButton.setEnabled(false);
			closingButton.setEnabled(false);
		}
	}


	private void loadProjects() {
		
		ListDataProvider<OpenProject> dataProvider = new ListDataProvider<>(TimeHelper.getOpenProjects(null));
		projectsTable.setDataProvider(dataProvider);
	}


	public Map<String, String> getConfiguration() {
		return configuration;
	}


	public void setConfiguration(Map<String, String> configuration) {
		this.configuration = configuration;
	}
	
	


	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		return mainLayout;
	}


	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("100.0%");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// projectsTable
		projectsTable = new Grid<OpenProject>();
		projectsTable.setWidth("-1px");
		projectsTable.setHeight("100.0%");
		horizontalLayout_1.addComponent(projectsTable);
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		horizontalLayout_1.addComponent(verticalLayout_2);
		
		return horizontalLayout_1;
	}


	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setWidth("-1px");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(true);
		verticalLayout_2.setSpacing(true);
		
		// previewInvoiceButton
		previewInvoiceButton = new Button();
		previewInvoiceButton.setCaption("Vorschau Rechnung");
		UIHelper.setImmediate(previewInvoiceButton, true);
		previewInvoiceButton.setWidth("200px");
		previewInvoiceButton.setHeight("-1px");
		verticalLayout_2.addComponent(previewInvoiceButton);
		
		// closingButton
		closingButton = new Button();
		closingButton.setCaption("Monatsabschluss");
		UIHelper.setImmediate(closingButton, true);
		closingButton.setWidth("200px");
		closingButton.setHeight("-1px");
		verticalLayout_2.addComponent(closingButton);
		
		return verticalLayout_2;
	}

}
