package org.mgnl.nicki.consulting.views;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.mgnl.nicki.consulting.core.helper.TimeHelper;
import org.mgnl.nicki.consulting.core.model.Customer;
import org.mgnl.nicki.consulting.core.model.Member;
import org.mgnl.nicki.consulting.core.model.Person;
import org.mgnl.nicki.consulting.core.model.Project;
import org.mgnl.nicki.consulting.data.MemberWrapper;
import org.mgnl.nicki.db.context.DBContext;
import org.mgnl.nicki.db.context.DBContextManager;
import org.mgnl.nicki.db.profile.InitProfileException;
import org.mgnl.nicki.vaadin.base.helper.UIHelper;
import org.mgnl.nicki.vaadin.base.menu.application.View;
import org.mgnl.nicki.vaadin.db.editor.DbBeanCloseListener;
import org.mgnl.nicki.vaadin.db.editor.DbBeanViewer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.Component;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class CustomersView extends BaseView implements View {
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private VerticalLayout membersLayout;
	@AutoGenerated
	private VerticalLayout memberLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_6;
	@AutoGenerated
	private VerticalLayout verticalLayout_4;
	@AutoGenerated
	private Button deleteMemberButton;
	@AutoGenerated
	private Button newMemberButton;
	@AutoGenerated
	private Grid<MemberWrapper> membersTable;
	@AutoGenerated
	private VerticalLayout projectsLayout;
	@AutoGenerated
	private VerticalLayout projectLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private Button deleteProjectButton;
	@AutoGenerated
	private Button newProjectButton;
	@AutoGenerated
	private Grid<Project> projectsTable;
	@AutoGenerated
	private VerticalLayout customersLayout;
	@AutoGenerated
	private VerticalLayout customerLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Button deleteCustomerButton;
	@AutoGenerated
	private Button newCustomerButton;
	@AutoGenerated
	private Grid<Customer> customersTable;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1751419839762448157L;
	private static final Logger LOG = LoggerFactory.getLogger(CustomersView.class);
	private boolean isInit;
	
	private Window newCustomerWindow;
	private Window newProjectWindow;
	private Window newMemberWindow;
	private Window selectPersonWindow;

	public CustomersView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		newCustomerButton.addClickListener(event ->	showNewCustomerView());
		
		deleteCustomerButton.addClickListener(event -> deleteCustomer());
		customersTable.asSingleSelect();
		customersTable.addSelectionListener(event -> {
			if (event.getFirstSelectedItem()  != null) {
				showCustomer(event.getFirstSelectedItem());
			} else {
				hideCustomer();
			}
		});

		newProjectButton.addClickListener(event -> showNewProjectView());
		deleteProjectButton.addClickListener(event -> deleteProject());
		projectsTable.asSingleSelect();
		projectsTable.addSelectionListener(event -> {
			if (event.getFirstSelectedItem() != null) {
				showProject(event.getFirstSelectedItem());
			} else {
				hideProject();
			}
		});

		newMemberButton.addClickListener(event -> showNewMemberView());
		deleteMemberButton.addClickListener(event -> deleteMember());
		membersTable.asSingleSelect();
		membersTable.addSelectionListener(event -> {
			if (event.getFirstSelectedItem() != null) {
				showMember(event.getFirstSelectedItem());
			} else {
				hideMember();
			}
		});
	}

	private void deleteMember() {
		MemberWrapper memberWrapper = (MemberWrapper) membersTable.getSelectedItems().iterator().next();
		if (memberWrapper == null) {
			Notification.show("Bitte erst Projektmitglied auswählen", Type.HUMANIZED_MESSAGE);
		} else {
			try {
				if (TimeHelper.hasTimeEntries(memberWrapper.getMember())) {
					Notification.show("Es gibt Buchungen für diese Projektmitglied", Type.HUMANIZED_MESSAGE);
				} else {
					TimeHelper.delete(memberWrapper.getMember());
					showMembersLayout(false);
					showProjectsLayout(false);
					loadCustomers();
				}
			} catch (SQLException | InitProfileException e) {
				LOG.error("Error accessing db", e);
				Notification.show("Das Projektmitglied konnte nicht gelöscht werden", Type.ERROR_MESSAGE);
			}
		}
	}

	private void deleteProject() {
		Optional<Project> projectOptional = getSelectedItem(projectsTable);
		if (!projectOptional.isPresent()) {
			Notification.show("Bitte erst Projekt auswählen", Type.HUMANIZED_MESSAGE);
		} else {
			Project project = projectOptional.get();
			try {
				if (TimeHelper.hasMembers(project)) {
					Notification.show("Das Projekt hat noch Projektmitglieder", Type.HUMANIZED_MESSAGE);
				} else {
					TimeHelper.delete(project);
					showMembersLayout(false);
					showProjectsLayout(false);
					loadCustomers();

				}
			} catch (SQLException | InitProfileException e) {
				LOG.error("Error accessing db", e);
				Notification.show("Das Projekt konnte nicht gelöscht werden", Type.ERROR_MESSAGE);
			}
		}
	}

	private void deleteCustomer() {
		Optional<Customer> customerOptional = getSelectedItem(customersTable);
		if (!customerOptional.isPresent()) {
			Notification.show("Bitte erst Kunde auswählen", Type.HUMANIZED_MESSAGE);
		} else {
			Customer customer = customerOptional.get();
			try {
				if (TimeHelper.hasProjects(customer)) {
					Notification.show("Der Kunde besitzt noch Projekte", Type.HUMANIZED_MESSAGE);
				} else {
					TimeHelper.delete(customer);
					showMembersLayout(false);
					showProjectsLayout(false);
					loadCustomers();
				}
			} catch (SQLException | InitProfileException e) {
				LOG.error("Error accessing db", e);
				Notification.show("Der Kunde konnte nicht gelöscht werden", Type.ERROR_MESSAGE);
			}
		}
	}

	private void hideCustomer() {
		customerLayout.removeAllComponents();
		showProjectsLayout(false);
		showMembersLayout(false);
	}

	private void showCustomer(Optional<Customer> customer) {
		if (customer.isPresent()) {
			showProjectsLayout(false);
			showMembersLayout(false);
			DbBeanViewer beanViewer = new DbBeanViewer(new DbBeanCloseListener() {
				
				@Override
				public void close(Component component) {
					hideCustomer();
					loadCustomers();
				}
			});
			beanViewer.setDbContextName("projects");
			beanViewer.setWidth("400px");
			beanViewer.setDbBean(customer);
			customerLayout.removeAllComponents();
			customerLayout.addComponent(beanViewer);
			showProjects(customer);
		}
	}

	private void showProjects(Optional<Customer> customer) {
		if (customer.isPresent()) {
			showProjectsLayout(true);
			loadProjects(customer);
		}
	}

	private void showNewCustomerView() {
		DbBeanViewer beanViewer = new DbBeanViewer(new DbBeanCloseListener() {
			
			@Override
			public void close(Component component) {
				UI.getCurrent().removeWindow(newCustomerWindow);
				hideCustomer();
				loadCustomers();
			}
		});
		beanViewer.setDbContextName("projects");
		beanViewer.setWidth("400px");
		try {
			beanViewer.init(Customer.class);
		} catch (InstantiationException | IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		newCustomerWindow = new Window("Neuer Kunde", beanViewer);
		newCustomerWindow.setModal(true);
		UI.getCurrent().addWindow(newCustomerWindow);
	}

	private void hideProject() {
		projectLayout.removeAllComponents();
		showProjectsLayout(true);
		showMembersLayout(false);
	}

	private void showProject(Optional<Project> project) {
		if (project.isPresent()) {
			DbBeanViewer beanViewer = new DbBeanViewer(new DbBeanCloseListener() {
				
				@Override
				public void close(Component component) {
					hideProject();
					loadProjects(getSelectedItem(customersTable));
				}
			});
			beanViewer.setDbContextName("projects");
			beanViewer.setWidth("400px");
			beanViewer.setDbBean(project);
			
			projectLayout.removeAllComponents();
			projectLayout.addComponent(beanViewer);
			showMembers(project);
		}
	}

	private void showMembers(Optional<Project> project) {
		showMembersLayout(true);
		loadMembers(project);
	}

	private void showNewProjectView() {
		Optional<Customer> customer = getSelectedItem(customersTable);
		if (customer.isPresent()) {
			DbBeanViewer beanViewer = new DbBeanViewer(new DbBeanCloseListener() {
				
				@Override
				public void close(Component component) {
					UI.getCurrent().removeWindow(newProjectWindow);
					hideProject();
					loadProjects(getSelectedItem(customersTable));
				}
			});
			beanViewer.setDbContextName("projects");
			beanViewer.setWidth("400px");
			try {
				beanViewer.init(Project.class, customer.get());
			} catch (InstantiationException | IllegalAccessException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			newProjectWindow = new Window("Neues Projekt", beanViewer);
			newProjectWindow.setModal(true);
			UI.getCurrent().addWindow(newProjectWindow);
		}
	}

	private void showNewMemberView() {
		PersonSelector selector = new PersonSelector(person -> {
			UI.getCurrent().removeWindow(selectPersonWindow);
			setPerson(person);
			
		});
		selector.init();
		selectPersonWindow = new Window("Person wählen", selector);
		selectPersonWindow.setModal(true);
		UI.getCurrent().addWindow(selectPersonWindow);
	}

	private void setPerson(Person person) {
		Optional<Project> project = getSelectedItem(projectsTable);
		DbBeanViewer beanViewer = new DbBeanViewer(new DbBeanCloseListener() {
			
			@Override
			public void close(Component component) {
				UI.getCurrent().removeWindow(newMemberWindow);
				hideMember();
				loadMembers(getSelectedItem(projectsTable));
			}
		});
		beanViewer.setDbContextName("projects");
		try {
			beanViewer.init(Member.class, project.isPresent()?project.get():null, person);
		} catch (InstantiationException | IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		newMemberWindow = new Window("Neues Projektmitglied", beanViewer);
		newMemberWindow.setModal(true);
		UI.getCurrent().addWindow(newMemberWindow);
	}

	private void hideMember() {
		memberLayout.removeAllComponents();
	}

	private void showMember(Optional<MemberWrapper> memberWrapper) {
		if (memberWrapper.isPresent()) {
			DbBeanViewer beanViewer = new DbBeanViewer(new DbBeanCloseListener() {
				
				@Override
				public void close(Component component) {
					hideMember();
					loadMembers(getSelectedItem(projectsTable));
				}
			});
			beanViewer.setDbContextName("projects");
			beanViewer.setWidth("400px");
			beanViewer.setDbBean(memberWrapper.get().getMember());
			
			memberLayout.removeAllComponents();
			memberLayout.addComponent(beanViewer);
		}
	}

	@Override
	public void init() {
		if (!isInit) {

			projectsTable.addColumn(Project::getName).setCaption("Projekt");
			membersTable.addColumn(MemberWrapper::getPersonName).setCaption("Mitglied");

			customersTable.addColumn(Customer::getName).setCaption("Name");
			customersTable.addColumn(Customer::getAlias).setCaption("Alias");
			customersTable.addColumn(Customer::getCity).setCaption("Stadt");

			loadCustomers();
			isInit = true;
			showCustomersLayout(true);
			showProjectsLayout(false);
			showMembersLayout(false);
		}
	}

	private void showCustomersLayout(boolean show) {
		customersLayout.setVisible(show);
		if (!show) {
			showProjectsLayout(false);
		}
		
	}

	private void showProjectsLayout(boolean show) {
		projectsLayout.setVisible(show);
		if (!show) {
			projectLayout.removeAllComponents();
			showMembersLayout(false);
		}
	}

	private void showMembersLayout(boolean show) {
		membersLayout.setVisible(show);
		if (!show) {
			memberLayout.removeAllComponents();
		}
	}

	private void loadCustomers() {
		Customer customer = new Customer();
		try (DBContext dbContext = DBContextManager.getContext("projects")) {
			List<Customer> customers = dbContext.loadObjects(customer, false);
			customersTable.setItems(customers);

		} catch (InstantiationException | IllegalAccessException | SQLException | InitProfileException e) {
			LOG.error("Could not load customers", e);
		}
		
	}

	private void loadProjects(Optional<Customer> customer) {
		if (customer.isPresent()) {
			Project project = new Project();
			project.setCustomerId(customer.get().getId());
			try (DBContext dbContext = DBContextManager.getContext("projects")) {
				List<Project> projects = dbContext.loadObjects(project, false);
				projectsTable.setItems(projects);
			} catch (InstantiationException | IllegalAccessException | SQLException | InitProfileException e) {
				LOG.error("Could not load projects", e);
			}
		}
	}

	private void loadMembers(Optional<Project> project) {
		if (project.isPresent()) {
			Member member= new Member();
			member.setProjectId(project.get().getId());
			try (DBContext dbContext = DBContextManager.getContext("projects")) {
				List<Member> members= dbContext.loadObjects(member, true);
				List<MemberWrapper> memberWrappers = new ArrayList<>();
				for (Member m : members) {
					memberWrappers.add(new MemberWrapper(m));
				}
				membersTable.setItems(memberWrappers);
			} catch (InstantiationException | IllegalAccessException | SQLException | InitProfileException e) {
				LOG.error("Could not load members", e);
			}		
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("100.0%");
		horizontalLayout_1.setMargin(false);
		
		// customersLayout
		customersLayout = buildCustomersLayout();
		horizontalLayout_1.addComponent(customersLayout);
		
		// projectsLayout
		projectsLayout = buildProjectsLayout();
		horizontalLayout_1.addComponent(projectsLayout);
		
		// membersLayout
		membersLayout = buildMembersLayout();
		horizontalLayout_1.addComponent(membersLayout);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildCustomersLayout() {
		// common part: create layout
		customersLayout = new VerticalLayout();
		customersLayout.setWidth("-1px");
		customersLayout.setHeight("-1px");
		customersLayout.setMargin(false);
		customersLayout.setSpacing(true);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		customersLayout.addComponent(horizontalLayout_3);
		
		// customerLayout
		customerLayout = new VerticalLayout();
		customerLayout.setWidth("100.0%");
		customerLayout.setHeight("100.0%");
		customerLayout.setMargin(false);
		customersLayout.addComponent(customerLayout);
		
		return customersLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setWidth("-1px");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(true);
		horizontalLayout_3.setSpacing(true);
		
		// customersTable
		customersTable = new Grid<Customer>();
		customersTable.setCaption("Kunden");
		UIHelper.setImmediate(customersTable, true);
		customersTable.setWidth("-1px");
		customersTable.setHeight("-1px");
		horizontalLayout_3.addComponent(customersTable);
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		horizontalLayout_3.addComponent(verticalLayout_2);
		
		return horizontalLayout_3;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setWidth("-1px");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(true);
		verticalLayout_2.setSpacing(true);
		
		// newCustomerButton
		newCustomerButton = new Button();
		newCustomerButton.setCaption("Neu");
		UIHelper.setImmediate(newCustomerButton, true);
		newCustomerButton.setWidth("-1px");
		newCustomerButton.setHeight("-1px");
		verticalLayout_2.addComponent(newCustomerButton);
		
		// deleteCustomerButton
		deleteCustomerButton = new Button();
		deleteCustomerButton.setCaption("Löschen");
		deleteCustomerButton.setWidth("-1px");
		deleteCustomerButton.setHeight("-1px");
		verticalLayout_2.addComponent(deleteCustomerButton);
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private VerticalLayout buildProjectsLayout() {
		// common part: create layout
		projectsLayout = new VerticalLayout();
		projectsLayout.setWidth("-1px");
		projectsLayout.setHeight("-1px");
		projectsLayout.setMargin(false);
		
		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		projectsLayout.addComponent(horizontalLayout_4);
		
		// projectLayout
		projectLayout = new VerticalLayout();
		projectLayout.setWidth("100.0%");
		projectLayout.setHeight("100.0%");
		projectLayout.setMargin(false);
		projectsLayout.addComponent(projectLayout);
		
		return projectsLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setWidth("-1px");
		horizontalLayout_4.setHeight("-1px");
		horizontalLayout_4.setMargin(true);
		horizontalLayout_4.setSpacing(true);
		
		// projectsTable
		projectsTable = new Grid<Project>();
		projectsTable.setCaption("Projekte");
		UIHelper.setImmediate(projectsTable, true);
		projectsTable.setWidth("-1px");
		projectsTable.setHeight("-1px");
		horizontalLayout_4.addComponent(projectsTable);
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		horizontalLayout_4.addComponent(verticalLayout_3);
		
		return horizontalLayout_4;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setWidth("-1px");
		verticalLayout_3.setHeight("-1px");
		verticalLayout_3.setMargin(true);
		verticalLayout_3.setSpacing(true);
		
		// newProjectButton
		newProjectButton = new Button();
		newProjectButton.setCaption("Neu");
		UIHelper.setImmediate(newProjectButton, true);
		newProjectButton.setWidth("-1px");
		newProjectButton.setHeight("-1px");
		verticalLayout_3.addComponent(newProjectButton);
		
		// deleteProjectButton
		deleteProjectButton = new Button();
		deleteProjectButton.setCaption("Löschen");
		deleteProjectButton.setWidth("-1px");
		deleteProjectButton.setHeight("-1px");
		verticalLayout_3.addComponent(deleteProjectButton);
		
		return verticalLayout_3;
	}

	@AutoGenerated
	private VerticalLayout buildMembersLayout() {
		// common part: create layout
		membersLayout = new VerticalLayout();
		membersLayout.setWidth("-1px");
		membersLayout.setHeight("-1px");
		membersLayout.setMargin(false);
		membersLayout.setSpacing(true);
		
		// horizontalLayout_6
		horizontalLayout_6 = buildHorizontalLayout_6();
		membersLayout.addComponent(horizontalLayout_6);
		
		// memberLayout
		memberLayout = new VerticalLayout();
		memberLayout.setWidth("100.0%");
		memberLayout.setHeight("100.0%");
		memberLayout.setMargin(false);
		membersLayout.addComponent(memberLayout);
		
		return membersLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_6() {
		// common part: create layout
		horizontalLayout_6 = new HorizontalLayout();
		horizontalLayout_6.setWidth("-1px");
		horizontalLayout_6.setHeight("-1px");
		horizontalLayout_6.setMargin(true);
		horizontalLayout_6.setSpacing(true);
		
		// membersTable
		membersTable = new Grid<MemberWrapper>();
		membersTable.setCaption("Projektmitglieder");
		UIHelper.setImmediate(membersTable, true);
		membersTable.setWidth("-1px");
		membersTable.setHeight("-1px");
		horizontalLayout_6.addComponent(membersTable);
		
		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		horizontalLayout_6.addComponent(verticalLayout_4);
		
		return horizontalLayout_6;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setWidth("-1px");
		verticalLayout_4.setHeight("-1px");
		verticalLayout_4.setMargin(true);
		verticalLayout_4.setSpacing(true);
		
		// newMemberButton
		newMemberButton = new Button();
		newMemberButton.setCaption("Neu");
		UIHelper.setImmediate(newMemberButton, true);
		newMemberButton.setWidth("-1px");
		newMemberButton.setHeight("-1px");
		verticalLayout_4.addComponent(newMemberButton);
		
		// deleteMemberButton
		deleteMemberButton = new Button();
		deleteMemberButton.setCaption("Löschen");
		deleteMemberButton.setWidth("-1px");
		deleteMemberButton.setHeight("-1px");
		verticalLayout_4.addComponent(deleteMemberButton);
		
		return verticalLayout_4;
	}

}
