package org.mgnl.nicki.consulting.views;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import org.mgnl.nicki.consulting.core.helper.TimeHelper;
import org.mgnl.nicki.consulting.core.model.Customer;
import org.mgnl.nicki.consulting.core.model.Member;
import org.mgnl.nicki.consulting.core.model.Project;
import org.mgnl.nicki.consulting.data.MemberWrapper;
import org.mgnl.nicki.consulting.data.TreeObject;
import org.mgnl.nicki.consulting.data.TreeObjectWrapper;
import org.mgnl.nicki.db.context.DBContext;
import org.mgnl.nicki.db.context.DBContextManager;
import org.mgnl.nicki.db.profile.InitProfileException;
import org.mgnl.nicki.vaadin.base.application.NickiApplication;
import org.mgnl.nicki.vaadin.base.menu.application.View;
import org.mgnl.nicki.vaadin.db.editor.DbBeanCloseListener;
import org.mgnl.nicki.vaadin.db.editor.DbBeanViewer;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.contextmenu.GridContextMenu;
import com.vaadin.data.TreeData;
import com.vaadin.data.provider.TreeDataProvider;
import com.vaadin.ui.AbstractLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Notification;
import com.vaadin.ui.TreeGrid;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Notification.Type;

import lombok.extern.slf4j.Slf4j;

@Slf4j
@SuppressWarnings("serial")
public class CustomersTreeView extends CustomComponent implements View {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel;
	
	private TreeGrid<TreeObject> tree;
	private TreeDataProvider<TreeObject> treeDataProvider;
	private VerticalLayout treeCanvas;
	private VerticalLayout canvas;
	private boolean isInit;
	
	private List<Customer> customers;
	private Map<Customer, Project> projects = new HashMap<>();
	private Map<Project, MemberWrapper> members = new HashMap<>();
	private Window editWindow;


	public CustomersTreeView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		init();

	}

	public void init() {
		if (!isInit) {
			
			isInit = true;
		}
		
		treeCanvas.removeAllComponents();
		canvas.removeAllComponents();
		
		tree = new TreeGrid<>();
		tree.setSizeFull();

		collectData();
		tree.setDataProvider(treeDataProvider);
		tree.addColumn(TreeObject::getDisplayName);
		tree.addSelectionListener(event -> {
			canvas.removeAllComponents();
			Optional<TreeObject> itemOptional = event.getFirstSelectedItem();
			if (itemOptional.isPresent()) {
				TreeObject target = itemOptional.get().getObject();
				if (target instanceof MemberWrapper) {
					target = ((MemberWrapper) target).getMember();
				}
				showEditView(canvas, target);
			}
		});
		// newCustomerButton
		Button newCustomerButton = new Button();
		newCustomerButton.setCaption("Neuer Kunde");
		newCustomerButton.setWidth("-1px");
		newCustomerButton.setHeight("-1px");
		newCustomerButton.addClickListener(event -> showEditView(Customer.class, Optional.empty(), "Neuer Kunde", "Kunde bearbeiten"));
		treeCanvas.addComponent(newCustomerButton);
		
		treeCanvas.addComponent(tree);
		treeCanvas.setExpandRatio(tree, 1);

        GridContextMenu<TreeObject> contextMenu = new GridContextMenu<>(tree);
        // handle item right-click
        contextMenu.addGridBodyContextMenuListener(event -> {
            event.getContextMenu().removeItems();
            if (event.getItem() != null) {
            	TreeObject item = event.getItem();
            	tree.select(item);
            	TreeObject target = item.getObject();
            	
            	if (target instanceof Customer) {
					event.getContextMenu().addItem("Löschen", selectedItem -> deleteCustomer(Optional.of((Customer) target)));
					event.getContextMenu().addItem("Neues Projekt", selectedItem -> showEditView(Project.class, Optional.empty(), "Neues Projekt", "Projekt bearbeiten", target));
            	} else if (target instanceof Project) {
					event.getContextMenu().addItem("Löschen", selectedItem -> deleteProject(Optional.of((Project) target)));
					event.getContextMenu().addItem("Neues Projektmitglied", selectedItem -> showEditView(Member.class, Optional.empty(), "Neues Projektmitglied", "Projektmitglied bearbeiten", target));
            	} else if (target instanceof MemberWrapper) {
					event.getContextMenu().addItem("Löschen", selectedItem -> deleteMember(Optional.of((MemberWrapper) target)));
            	}
            }
        });
		
	}

	private <T> void showEditView(AbstractLayout layout, T object) {
		DbBeanViewer beanViewer = new DbBeanViewer(new DbBeanCloseListener() {
			
			@Override
			public void close(Component component) {
				init();
			}
		});
		beanViewer.setDbContextName("projects");
		beanViewer.setHeightFull();
		beanViewer.setWidthFull();
		if (object != null) {
			beanViewer.setDbBean(object);
			layout.addComponent(beanViewer);
		}
	}

	private void deleteCustomer(Optional<Customer> customerOptional ) {
		if (!customerOptional.isPresent()) {
			Notification.show("Bitte erst Kunde auswählen", Type.HUMANIZED_MESSAGE);
		} else {
			Customer customer = customerOptional.get();
			try {
				if (TimeHelper.hasProjects(customer)) {
					Notification.show("Der Kunde besitzt noch Projekte", Type.HUMANIZED_MESSAGE);
				} else {
					TimeHelper.delete(customer);
					init();
				}
			} catch (SQLException | InitProfileException e) {
				log.error("Error accessing db", e);
				Notification.show("Der Kunde konnte nicht gelöscht werden", Type.ERROR_MESSAGE);
			}
		}
	}

	private void deleteProject(Optional<Project> projectOptional) {
		if (!projectOptional.isPresent()) {
			Notification.show("Bitte erst Projekt auswählen", Type.HUMANIZED_MESSAGE);
		} else {
			Project project = projectOptional.get();
			try {
				if (TimeHelper.hasMembers(project)) {
					Notification.show("Das Projekt hat noch Projektmitglieder", Type.HUMANIZED_MESSAGE);
				} else {
					TimeHelper.delete(project);
					init();
				}
			} catch (SQLException | InitProfileException e) {
				log.error("Error accessing db", e);
				Notification.show("Das Projekt konnte nicht gelöscht werden", Type.ERROR_MESSAGE);
			}
		}
	}

	private void deleteMember(Optional<MemberWrapper> memberWrapperOptional) {
		if (!memberWrapperOptional.isPresent()) {
			Notification.show("Bitte erst Projektmitglied auswählen", Type.HUMANIZED_MESSAGE);
		} else {
			try {
				if (TimeHelper.hasTimeEntries(memberWrapperOptional.get().getMember())) {
					Notification.show("Es gibt Buchungen für diese Projektmitglied", Type.HUMANIZED_MESSAGE);
				} else {
					TimeHelper.delete(memberWrapperOptional.get().getMember());
					init();
				}
			} catch (SQLException | InitProfileException e) {
				log.error("Error accessing db", e);
				Notification.show("Das Projektmitglied konnte nicht gelöscht werden", Type.ERROR_MESSAGE);
			}
		}
	}
	
	private <T> void showEditView(Class<T> clazz, Optional<T> object, String newCaption, String editCaption, Object... foreignObjects) {
		DbBeanViewer beanViewer = new DbBeanViewer(new DbBeanCloseListener() {
			
			@Override
			public void close(Component component) {
				UI.getCurrent().removeWindow(editWindow);
				init();
			}
		});
		beanViewer.setDbContextName("projects");
		beanViewer.setHeightFull();
		beanViewer.setWidth("400px");
		String windowTitle;
		if (!object.isPresent()) {
			try {
				beanViewer.init(clazz, foreignObjects);
			} catch (InstantiationException | IllegalAccessException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			windowTitle = newCaption;
		} else {
			beanViewer.setDbBean(object.get());
			windowTitle = editCaption;
		}
		editWindow = new Window(windowTitle, beanViewer);
		editWindow.setModal(true);
		editWindow.setHeightFull();
		UI.getCurrent().addWindow(editWindow);
	}

	private void collectData() {
		this.projects.clear();
		this.members.clear();
		TreeData<TreeObject> treeData = new TreeData<TreeObject>();
		treeDataProvider = new TreeDataProvider<>(treeData);
		try (DBContext dbContext = DBContextManager.getContext("projects")) {
			customers = loadCustomers(dbContext);
			if (customers != null) {
				customers.stream().forEach(customer -> {
					TreeObjectWrapper<Customer> customerWrapper = new TreeObjectWrapper<Customer>(customer);
					treeData.addItem(null, customerWrapper);
					List<Project> projects;
					try {
						projects = loadProjects(dbContext, customer);
					} catch (InstantiationException | IllegalAccessException | SQLException | InitProfileException e) {
						log.error("Error reading project for customer: " + customer, e);
						projects = null;
					}
					if (projects != null) {
						projects.stream().forEach(project -> {
							this.projects.put(customer, project);
							TreeObjectWrapper<Project> projectWrapper = new TreeObjectWrapper<Project>(project);
							treeData.addItem(customerWrapper, projectWrapper);
							List<Member> members;
							try {
								members = loadMembers(dbContext, project);
							} catch (InstantiationException | IllegalAccessException | SQLException
									| InitProfileException e) {
								log.error("Error reading members for project: " + project, e);
								members = null;
							}
							if (members != null) {
								members.stream().forEach(member -> {
									MemberWrapper memberWrapper = new MemberWrapper(member);
									this.members.put(project, memberWrapper);
									treeData.addItem(projectWrapper, new TreeObjectWrapper<MemberWrapper>(memberWrapper));
									
								});
							}
						});
					}
				});
			}
			
		} catch (InstantiationException | IllegalAccessException | SQLException | InitProfileException e) {
			log.error("Could not load customers", e);
		}
		
	}

	private List<Customer> loadCustomers(DBContext dbContext) throws InstantiationException, IllegalAccessException, SQLException, InitProfileException {
		Customer customer = new Customer();
		return dbContext.loadObjects(customer, false);
	}

	private List<Project> loadProjects(DBContext dbContext, Customer customer) throws InstantiationException, IllegalAccessException, SQLException, InitProfileException {
		Project project = new Project();
		project.setCustomerId(customer.getId());
		return dbContext.loadObjects(project, false);
	}

	private List<Member> loadMembers(DBContext dbContext, Project project) throws InstantiationException, IllegalAccessException, SQLException, InitProfileException {
		Member member= new Member();
		member.setProjectId(project.getId());
		return dbContext.loadObjects(member, true);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setSizeFull();
		mainLayout.setMargin(false);
		mainLayout.setSpacing(false);
		
		// top-level component properties
		setSizeFull();
		
		// horizontalSplitPanel
		horizontalSplitPanel = new HorizontalSplitPanel();
		horizontalSplitPanel.setSizeFull();
		mainLayout.addComponent(horizontalSplitPanel);
		
		treeCanvas = new VerticalLayout();
		treeCanvas.setSizeFull();
		treeCanvas.setMargin(false);
		treeCanvas.setSpacing(true);
		horizontalSplitPanel.setFirstComponent(treeCanvas);
		
		canvas = new VerticalLayout();
		canvas.setSizeFull();
		canvas.setMargin(false);
		canvas.setSpacing(false);
		horizontalSplitPanel.setSecondComponent(canvas);
		
		
		return mainLayout;
	}

	@Override
	public boolean isModified() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void setApplication(NickiApplication arg0) {
		// TODO Auto-generated method stub
		
	}

}
