package org.mgnl.nicki.consulting.views;

import java.util.Map;

import org.apache.commons.lang.StringUtils;
import org.mgnl.nicki.consulting.core.helper.TimeHelper;
import org.mgnl.nicki.consulting.core.model.Customer;
import org.mgnl.nicki.consulting.core.model.Project;
import org.mgnl.nicki.consulting.data.InvoiceWrapper;
import org.mgnl.nicki.consulting.db.TimeSelectException;
import org.mgnl.nicki.core.config.Config;
import org.mgnl.nicki.core.data.Period;
import org.mgnl.nicki.vaadin.base.helper.UIHelper;
import org.mgnl.nicki.vaadin.base.menu.application.ConfigurableView;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.FileDownloader;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.renderers.ComponentRenderer;

public class InvoicesView extends BaseView implements ConfigurableView  {
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Grid<InvoiceWrapper> timeTable;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private HorizontalLayout filterLayout;
	@AutoGenerated
	private ComboBox<Project> projectComboBox;
	@AutoGenerated
	private ComboBox<Customer> customerComboBox;
	@AutoGenerated
	private ComboBox<PERIOD> timeComboBox;


	private static final long serialVersionUID = -2330776406366438437L;
	public static final String PROPERTY_BASE_DN = "nicki.templates.basedn";
	
	private enum TEMPLATE_TYPE {TEMPLATE, GROUP_OF_TEMPLATES, UNKNOWN}
	
	private boolean isInit;

	private FileDownloader pdfFileDownloader;
	Map<String, String> configuration;
	
	public InvoicesView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

	}


	@Override
	public void init() {
		if (!isInit) {
			initTimeComboBox(this.timeComboBox);
			customerComboBox.setEnabled(true);
			projectComboBox.setEnabled(true);
			
			timeTable.addColumn(InvoiceWrapper::getCustomerName).setCaption("Kunde");
			timeTable.addColumn(InvoiceWrapper::getProjectName).setCaption("Projekt");
			timeTable.addColumn(InvoiceWrapper::getStart).setCaption("von");
			timeTable.addColumn(InvoiceWrapper::getEnd).setCaption("bis");
			timeTable.addColumn(InvoiceWrapper::getInvoiceDate).setCaption("Rechnungsdatum");
			timeTable.addColumn(InvoiceWrapper::getInvoiceNumber).setCaption("Rechnungsnummer");
			timeTable.addColumn(InvoiceWrapper::getInvoiceDocument, new ComponentRenderer()).setCaption("Rechnung");
			timeTable.addColumn(InvoiceWrapper::getTimeSheetDocument, new ComponentRenderer()).setCaption("Zeitnachweis");
			timeTable.addColumn(InvoiceWrapper::getUndoButton, new ComponentRenderer()).setCaption("Storno");
			
			timeComboBox.addValueChangeListener(event -> {timeComboBoxChanged();});
			customerComboBox.addValueChangeListener(event -> {customerComboBoxChanged();});
			projectComboBox.addValueChangeListener(event -> {projectComboBoxChanged();});
			timeComboBoxChanged();
			isInit = true;
		}
		initCustomerComboBox();
		initProjectComboBox();
		loadInvoices();
	}
	
	@Override
	protected void reload() {
		loadInvoices();
	}


	private void timeComboBoxChanged() {
		initCustomerComboBox();
		initProjectComboBox();
		loadInvoices();
	}

	private void customerComboBoxChanged() {
		if (customerComboBox.getValue() != null) {
			projectComboBox.setValue(null);
		}
		initProjectComboBox();
		loadInvoices();
	}

	private void projectComboBoxChanged() {
		loadInvoices();
	}

	private void loadInvoices() {
		try {
			PERIOD p = (PERIOD) timeComboBox.getValue();
			Period period = null;
			if (p != null) {
				period = p.getPeriod();
				timeTable.setItems(getInvoiceWrappers(period, (Customer) customerComboBox.getValue(), (Project) projectComboBox.getValue()));
			}
		} catch (IllegalStateException | IllegalArgumentException | TimeSelectException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void initCustomerComboBox() {
	
		customerComboBox.setItems(TimeHelper.getAllCustomers());
		customerComboBox.setItemCaptionGenerator(Customer::getName);
	}


	private void initProjectComboBox() {
	
		projectComboBox.setItems();
		if (customerComboBox.getValue() != null) {
			projectComboBox.setItems(TimeHelper.getProjects((Customer) customerComboBox.getValue()));
			projectComboBox.setItemCaptionGenerator(Project::getName);
		}
	}

	public FileDownloader getPdfFileDownloader() {
		return pdfFileDownloader;
	}


	public void setPdfFileDownloader(FileDownloader pdfFileDownloader) {
		this.pdfFileDownloader = pdfFileDownloader;
	}


	public Map<String, String> getConfiguration() {
		return configuration;
	}


	public void setConfiguration(Map<String, String> configuration) {
		this.configuration = configuration;
	}
	
	protected TEMPLATE_TYPE getTemplateType() {
		if (getConfiguration() != null) {
			for(TEMPLATE_TYPE type : TEMPLATE_TYPE.values()) {
				if (StringUtils.equals(type.name(), getConfiguration().get("type"))) {
					return type;
				}
			}
		}
		return TEMPLATE_TYPE.UNKNOWN;
	}
	
	protected String getTemplatePath() {
		if (getConfiguration() != null && getConfiguration().get("path") != null) {
			return getConfiguration().get("path");
		}
		return Config.getString("nicki.consulting.report.default", "reports/timeReport/TimeReport");
	}
	
	


	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		mainLayout.addComponent(verticalLayout_2);
		
		// timeTable
		timeTable = new Grid<InvoiceWrapper>();
		timeTable.setWidth("100%");
		timeTable.setHeight("100.0%");
		mainLayout.addComponent(timeTable);
		mainLayout.setExpandRatio(timeTable, 1.0f);
		
		return mainLayout;
	}


	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setWidth("-1px");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(true);
		verticalLayout_2.setSpacing(true);
		
		// filterLayout
		filterLayout = buildFilterLayout();
		verticalLayout_2.addComponent(filterLayout);
		
		
		return verticalLayout_2;
	}


	@AutoGenerated
	private HorizontalLayout buildFilterLayout() {
		// common part: create layout
		filterLayout = new HorizontalLayout();
		filterLayout.setWidth("-1px");
		filterLayout.setHeight("-1px");
		filterLayout.setMargin(false);
		filterLayout.setSpacing(true);
		
		// timeComboBox
		timeComboBox = new ComboBox<>();
		timeComboBox.setCaption("Zeitraum");
		UIHelper.setImmediate(timeComboBox, true);
		timeComboBox.setWidth("-1px");
		timeComboBox.setHeight("-1px");
		filterLayout.addComponent(timeComboBox);
		
		// customerComboBox
		customerComboBox = new ComboBox<>();
		customerComboBox.setCaption("Kunde");
		UIHelper.setImmediate(customerComboBox, true);
		customerComboBox.setWidth("-1px");
		customerComboBox.setHeight("-1px");
		filterLayout.addComponent(customerComboBox);
		
		// projectComboBox
		projectComboBox = new ComboBox<>();
		projectComboBox.setCaption("Projekt");
		UIHelper.setImmediate(projectComboBox, true);
		projectComboBox.setWidth("-1px");
		projectComboBox.setHeight("-1px");
		filterLayout.addComponent(projectComboBox);
		
		return filterLayout;
	}


}
