package org.mgnl.nicki.consulting.views;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.mgnl.nicki.consulting.core.helper.Constants;
import org.mgnl.nicki.consulting.core.helper.InvoiceHelper;
import org.mgnl.nicki.consulting.core.helper.TimeHelper;
import org.mgnl.nicki.consulting.core.model.Invoice;
import org.mgnl.nicki.consulting.core.model.Project;
import org.mgnl.nicki.consulting.core.model.Time;
import org.mgnl.nicki.consulting.db.OpenTimeSelectHandler;
import org.mgnl.nicki.consulting.db.TimeSelectException;
import org.mgnl.nicki.core.data.Period;
import org.mgnl.nicki.core.helper.DataHelper;
import org.mgnl.nicki.db.context.DBContext;
import org.mgnl.nicki.db.context.DBContextManager;
import org.mgnl.nicki.db.context.NotSupportedException;
import org.mgnl.nicki.db.context.PrimaryKey;
import org.mgnl.nicki.db.profile.InitProfileException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.FileDownloader;
import com.vaadin.server.StreamResource;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class PerformClosingView extends CustomComponent {
	private static final long serialVersionUID = -5801707593646769677L;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button downloadButton;
	@AutoGenerated
	private Button closeProjectButton;
	@AutoGenerated
	private PopupDateField nextStart;
	@AutoGenerated
	private TextField invoiceNumberTextField;

	private FileDownloader pdfFileDownloader;
	private Project project;
	private static final Logger LOG = LoggerFactory.getLogger(PerformClosingView.class);
	
	private ClosingView closingView;

	public PerformClosingView(ClosingView closingView, Project project, boolean closeProject) {
		this.closingView =closingView;
		this.project = project;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		downloadButton.setEnabled(false);
		if (!closeProject) {
			closeProjectButton.setVisible(false);
		}
		closeProjectButton.setEnabled(false);

		closeProjectButton.addClickListener(event -> close());
		invoiceNumberTextField.addValueChangeListener(event -> valuesChanged());
		nextStart.addValueChangeListener(event -> valuesChanged());
	}
	
	private void valuesChanged() {
		downloadButton.setEnabled(false);
		if (invoiceNumberTextField.getValue() != null && nextStart.getValue() != null) {
			generate();
			closeProjectButton.setEnabled(true);
		}
	}

	private void generate() {
		StreamResource pdfSource = createPDFStream();
		if (getPdfFileDownloader() != null) {
			downloadButton.removeExtension(getPdfFileDownloader());
		}
		setPdfFileDownloader(new FileDownloader(pdfSource));
		getPdfFileDownloader().extend(downloadButton);
		downloadButton.setEnabled(true);
		
	}

	private StreamResource createPDFStream() {
		return new StreamResource(
				() -> InvoiceHelper.renderInvoice(this.project, getInvoiceParams()),
				"Invoice_" + DataHelper.getMilli(new Date()) + ".pdf");
	}
	
	protected Map<String, Object> getInvoiceParams() {
		Map<String, Object> params = new HashMap<String, Object>();
		params.put("times", getTimes());
		params.put("invoiceNumber", invoiceNumberTextField.getValue());
		params.put("firstDay", this.project.getOpen());
		params.put("lastDay", new Date(nextStart.getValue().getTime() - InvoiceHelper.DAY_IN_MS));
		params.put("timeHelper", new TimeHelper());
		params.put("dataHelper", new DataHelper());
		params.put("today", DataHelper.getDisplayDay(new Date()));
		return params;
	}

	private List<Time> getTimes() {

		try (DBContext dbContext = DBContextManager.getContext(Constants.DB_CONTEXT_NAME)) {
			OpenTimeSelectHandler selectHandler = new OpenTimeSelectHandler(this.project, this.project.getOpen(), nextStart.getValue(), Constants.DB_CONTEXT_NAME);
			dbContext.select(selectHandler);
			return selectHandler.getList();
		} catch (SQLException | InitProfileException | TimeSelectException e) {
			LOG.error("Could not load open times", e);
		}
		return new ArrayList<>();
	}

	public FileDownloader getPdfFileDownloader() {
		return pdfFileDownloader;
	}


	public void setPdfFileDownloader(FileDownloader pdfFileDownloader) {
		this.pdfFileDownloader = pdfFileDownloader;
	}

	private void close() {
		Invoice invoice = new Invoice();
		
		Calendar start = Calendar.getInstance();
		start.setTime(this.project.getOpen());
		Period.setToBeginOfDay(start);
		invoice.setStart(start.getTime());
		
		Calendar end = Calendar.getInstance();
		end.setTime(nextStart.getValue());
		Period.setToBeginOfDay(end);
		invoice.setEnd(end.getTime());
		
		invoice.setInvoiceNumber(invoiceNumberTextField.getValue());
		invoice.setProjectId(this.project.getId());
		invoice.setInvoiceDate(new Date());
		try (DBContext dbContext = DBContextManager.getContext(Constants.DB_CONTEXT_NAME)) {
			// create invoice entry -> invoiceId
			PrimaryKey primaryKey = dbContext.create(invoice);
			long invoiceId = primaryKey.getLong("ID");
			// add invoiceId to times
			for (Time time : getTimes()) {
				time.setInvoiceId(invoiceId);
				dbContext.update(time, "invoiceId");
			}
			project.setOpen(end.getTime());
			dbContext.update(project, "open");
		} catch (SQLException | InitProfileException | NotSupportedException e) {
			LOG.error("Could not close the project", e);
			Notification.show("Projekt konnte nicht abgeschlossen werden", Type.ERROR_MESSAGE);
			return;
		}

		Notification.show("Projekt wurde erfolgreich abgeschlossen", Type.HUMANIZED_MESSAGE);
		closingView.finshClosing();
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// invoiceNumberTextField
		invoiceNumberTextField = new TextField();
		invoiceNumberTextField.setCaption("Rechnungsnummer");
		invoiceNumberTextField.setImmediate(true);
		invoiceNumberTextField.setWidth("-1px");
		invoiceNumberTextField.setHeight("-1px");
		mainLayout.addComponent(invoiceNumberTextField);
		
		// nextStart
		nextStart = new PopupDateField();
		nextStart.setCaption("Neuer Zeitraum ab");
		nextStart.setImmediate(true);
		nextStart.setWidth("-1px");
		nextStart.setHeight("-1px");
		nextStart.setInvalidAllowed(false);
		mainLayout.addComponent(nextStart);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// closeProjectButton
		closeProjectButton = new Button();
		closeProjectButton.setCaption("Abschlieﬂen");
		closeProjectButton.setImmediate(true);
		closeProjectButton.setWidth("-1px");
		closeProjectButton.setHeight("-1px");
		horizontalLayout_1.addComponent(closeProjectButton);
		
		// downloadButton
		downloadButton = new Button();
		downloadButton.setCaption("Rechnung");
		downloadButton.setImmediate(false);
		downloadButton.setWidth("-1px");
		downloadButton.setHeight("-1px");
		horizontalLayout_1.addComponent(downloadButton);
		
		return horizontalLayout_1;
	}

}
