package org.mgnl.nicki.consulting.views;

import java.sql.SQLException;
import java.util.List;

import org.mgnl.nicki.consulting.core.model.Person;
import org.mgnl.nicki.db.context.DBContext;
import org.mgnl.nicki.db.context.DBContextManager;
import org.mgnl.nicki.db.profile.InitProfileException;
import org.mgnl.nicki.vaadin.base.menu.application.View;
import org.mgnl.nicki.vaadin.db.editor.DbBeanCloseListener;
import org.mgnl.nicki.vaadin.db.editor.DbBeanViewer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.Component;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Grid.SelectionMode;

public class PersonsView extends BaseView implements View {
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private VerticalLayout personsLayout;
	@AutoGenerated
	private VerticalLayout personLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private Button newPersonButton;
	@AutoGenerated
	private Grid<Person> personsTable;


	private static final long serialVersionUID = 1751419839762448157L;
	private static final Logger LOG = LoggerFactory.getLogger(PersonsView.class);
	private boolean isInit;
	private Window newPersonWindow;

	public PersonsView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		newPersonButton.addClickListener(event -> {
			showNewPersonView();
		});
		personsTable.setSelectionMode(SelectionMode.SINGLE);
		personsTable.addSelectionListener(event -> {
			if (event.getFirstSelectedItem().isPresent()) {
				showPerson(event.getFirstSelectedItem().get());
			} else {
				hidePerson();
			}
		});
	}

	private void hidePerson() {
		personLayout.removeAllComponents();
	}

	private void showPerson(Person person) {
		DbBeanViewer beanViewer = new DbBeanViewer(new DbBeanCloseListener() {
			
			@Override
			public void close(Component component) {
				hidePerson();
				LoadPersons();
			}
		});
		beanViewer.setDbContextName("projects");
		beanViewer.setDbBean(person);
		personLayout.removeAllComponents();
		personLayout.addComponent(beanViewer);
	}

	private void showNewPersonView() {
		DbBeanViewer beanViewer = new DbBeanViewer(new DbBeanCloseListener() {
			
			@Override
			public void close(Component component) {
				UI.getCurrent().removeWindow(newPersonWindow);
				hidePerson();
				LoadPersons();
			}
		});
		beanViewer.setDbContextName("projects");
		try {
			beanViewer.init(Person.class);
		} catch (InstantiationException | IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		newPersonWindow = new Window("Neue Person", beanViewer);
		newPersonWindow.setModal(true);
		UI.getCurrent().addWindow(newPersonWindow);
	}

	@Override
	public void init() {
		if (!isInit) {
			personsTable.addColumn(Person::getName).setCaption("Name");
			LoadPersons();
			isInit = true;
			showPersonsLayout(true);
		}
	}

	private void showPersonsLayout(boolean show) {
		personsLayout.setVisible(show);
		
	}

	private void LoadPersons() {
		Person person = new Person();
		try (DBContext dbContext = DBContextManager.getContext("projects")) {
			List<Person> persons = dbContext.loadObjects(person, false);
			personsTable.setItems(persons);

		} catch (InstantiationException | IllegalAccessException | SQLException | InitProfileException e) {
			LOG.error("Could not load customers", e);
		}
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("100.0%");
		horizontalLayout_1.setMargin(false);
		
		// personsLayout
		personsLayout = buildPersonsLayout();
		horizontalLayout_1.addComponent(personsLayout);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildPersonsLayout() {
		// common part: create layout
		personsLayout = new VerticalLayout();
		personsLayout.setWidth("-1px");
		personsLayout.setHeight("-1px");
		personsLayout.setMargin(false);
		personsLayout.setSpacing(true);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		personsLayout.addComponent(horizontalLayout_3);
		
		// personLayout
		personLayout = new VerticalLayout();
		personLayout.setWidth("100.0%");
		personLayout.setHeight("100.0%");
		personLayout.setMargin(false);
		personsLayout.addComponent(personLayout);
		
		return personsLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setWidth("-1px");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(true);
		horizontalLayout_3.setSpacing(true);
		
		// personsTable
		personsTable = new Grid<>();
		personsTable.setWidth("-1px");
		personsTable.setHeight("-1px");
		horizontalLayout_3.addComponent(personsTable);
		
		// newPersonButton
		newPersonButton = new Button();
		newPersonButton.setCaption("Neu");
		newPersonButton.setWidth("-1px");
		newPersonButton.setHeight("-1px");
		horizontalLayout_3.addComponent(newPersonButton);
		
		return horizontalLayout_3;
	}

}
