package org.mgnl.nicki.consulting.views;

import java.util.List;

import org.mgnl.nicki.consulting.core.helper.PersonHelper;
import org.mgnl.nicki.consulting.core.model.Person;
import org.mgnl.nicki.vaadin.base.application.NickiApplication;
import org.mgnl.nicki.vaadin.base.menu.application.View;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Grid;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Grid.SelectionMode;

public class PersonSelector extends CustomComponent implements View {
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Grid<Person> personsTable;


	private static final long serialVersionUID = 1751419839762448157L;
	private boolean isInit;
	private PersonSelectorParent personSelectorParent;

	public PersonSelector(PersonSelectorParent personSelectorParent) {
		this.personSelectorParent = personSelectorParent;
	}

	@Override
	public void init() {
		if (!isInit) {
			buildMainLayout();
			mainLayout.setMargin(true);
			mainLayout.setWidth("100%");
			setCompositionRoot(mainLayout);
			personsTable.addColumn(Person::getName).setCaption("Name");
			personsTable.setSelectionMode(SelectionMode.SINGLE);
			personsTable.addSelectionListener(event -> {
				if (event.getFirstSelectedItem().isPresent()) {
					personSelectorParent.setPerson(event.getFirstSelectedItem().get());
				}
			});
			LoadPersons();
			isInit = true;
		}
	}

	private void LoadPersons() {
		
		List<Person> persons = PersonHelper.getPersons();
		personsTable.setItems(persons);
	}

	@Override
	public boolean isModified() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void setApplication(NickiApplication arg0) {
		// TODO Auto-generated method stub
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		
		// top-level component properties
		setWidth("100.0%");
		
		// personsTable
		personsTable = new Grid<Person>();
		personsTable.setWidth("-1px");
		personsTable.setHeight("-1px");
		mainLayout.addComponent(personsTable);
		
		return mainLayout;
	}

}
