package org.mgnl.nicki.consulting.views;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.parsers.ParserConfigurationException;

import org.apache.commons.lang.StringUtils;
import org.mgnl.nicki.consulting.core.helper.TimeHelper;
import org.mgnl.nicki.consulting.core.model.Customer;
import org.mgnl.nicki.consulting.core.model.Member;
import org.mgnl.nicki.consulting.core.model.Person;
import org.mgnl.nicki.consulting.core.model.Project;
import org.mgnl.nicki.consulting.core.model.Time;
import org.mgnl.nicki.consulting.data.BeanContainerDataSource;
import org.mgnl.nicki.consulting.data.TimeWrapper;
import org.mgnl.nicki.consulting.data.TimeWrapperItemSorter;
import org.mgnl.nicki.consulting.db.TimeSelectException;
import org.mgnl.nicki.core.auth.InvalidPrincipalException;
import org.mgnl.nicki.core.config.Config;
import org.mgnl.nicki.core.context.AppContext;
import org.mgnl.nicki.core.helper.DataHelper;
import org.mgnl.nicki.dynamic.objects.objects.Template;
import org.mgnl.nicki.report.XlsDocuHelper;
import org.mgnl.nicki.template.engine.ConfigurationFactory.TYPE;
import org.mgnl.nicki.template.engine.TemplateEngine;
import org.mgnl.nicki.vaadin.base.helper.UIHelper;
import org.mgnl.nicki.vaadin.base.menu.application.ConfigurableView;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.xml.sax.SAXException;

import com.itextpdf.text.DocumentException;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.FileDownloader;
import com.vaadin.server.StreamResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.vaadin.v7.ui.Table;
import com.vaadin.ui.VerticalLayout;

import freemarker.template.TemplateException;

public class ReportsView extends BaseView implements ConfigurableView  {
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Table timeTable;
	@AutoGenerated
	private HorizontalLayout summaryLayout;
	@AutoGenerated
	private Label daysLabel;
	@AutoGenerated
	private Label hoursLabel;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private HorizontalLayout reportsLayout;
	@AutoGenerated
	private Button downloadPdfButton;
	@AutoGenerated
	private Button downloadXlsButton;
	@AutoGenerated
	private ComboBox<Template> reportComboBox;
	@AutoGenerated
	private HorizontalLayout filterLayout;
	@AutoGenerated
	private ComboBox<Project> projectComboBox;
	@AutoGenerated
	private ComboBox<Customer> customerComboBox;
	@AutoGenerated
	private ComboBox<PERIOD> timeComboBox;
	@AutoGenerated
	private ComboBox personComboBox;

	private static final long serialVersionUID = -2330776406366438437L;
	private static final Logger LOG = LoggerFactory.getLogger(ReportsView.class);

	public static final String PROPERTY_BASE_DN = "nicki.templates.basedn";
	
	private enum TEMPLATE_TYPE {TEMPLATE, GROUP_OF_TEMPLATES, UNKNOWN}
	
	private boolean isInit;

	private FileDownloader pdfFileDownloader;

	private FileDownloader xlsFileDownloader;
	
	private Collection<Member> members;
	
	private Collection<Customer> customers;
	
	private Collection<Project> projects;
	private BeanContainerDataSource<TimeWrapper> timeContainerDataSource;
	Map<String, String> configuration;
	
	public ReportsView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

	}


	@Override
	public void init() {
		if (!isInit) {
			try {
				initReportComboBox();
			} catch (InvalidPrincipalException e) {
				LOG.error("Error init reportComboBox", e);
			}

			reportComboBox.addValueChangeListener(event -> { timeComboBoxChanged(); });
			initTimeComboBox(this.timeComboBox);
			try {
				initPersonComboBox(this.personComboBox, ALL.TRUE);
			} catch (NoValidPersonException | NoApplicationContextException e) {
				LOG.error("Error init personComboBox", e);
			}
			personComboBox.addValueChangeListener(event -> { timeComboBoxChanged(); });
			customerComboBox.setEnabled(true);
			projectComboBox.setEnabled(true);

			downloadPdfButton.setEnabled(false);
			downloadXlsButton.setEnabled(false);
			
			timeContainerDataSource = new BeanContainerDataSource<>(TimeWrapper.class);
			timeContainerDataSource.setItemSorter(new TimeWrapperItemSorter());
			timeTable.setContainerDataSource(timeContainerDataSource);
			timeTable.setVisibleColumns("person", "member", "day", "start", "end", "pause", "hours", "customerReport", "textString");
			timeTable.setColumnHeaders("Person", "Projekt", "Datum", "von", "bis", "Pause", "Stunden", "Bei Kunde erfasst", "Tätigkeit");
			
			timeComboBox.addValueChangeListener(event -> {timeComboBoxChanged();});
			customerComboBox.addValueChangeListener(event -> {customerComboBoxChanged();});
			projectComboBox.addValueChangeListener(event -> {projectComboBoxChanged();});
			timeComboBoxChanged();
			isInit = true;
		}
		try {
			initPersonData();
		} catch (NoValidPersonException | NoApplicationContextException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		initCustomerComboBox();
		initProjectComboBox();
		loadTimes();
	}

	private void initReportComboBox() throws InvalidPrincipalException {
		reportComboBox.setItems();
		reportComboBox.setItemCaptionGenerator(Template::getName);
		if (getTemplateType() == TEMPLATE_TYPE.TEMPLATE)  {
			
			Template template = loadTemplate(getTemplatePath());
			reportComboBox.setItems(template);
			reportComboBox.setValue(template);
		} else if (getTemplateType() == TEMPLATE_TYPE.GROUP_OF_TEMPLATES) {

			List<Template> templates = loadTemplates(getTemplatePath());
			reportComboBox.setItems(templates);
			if (templates != null) {
				reportComboBox.setSelectedItem(templates.get(0));
			}
		}
		reportComboBox.setEmptySelectionAllowed(false);
	}


	private Template loadTemplate(String templatePath) throws InvalidPrincipalException {
		String parts[] = StringUtils.split(templatePath, "/");
		StringBuilder sb = new StringBuilder();
		sb.insert(0, getTemplateBaseDn());
		for (String part : parts) {
			sb.insert(0, ",");
			sb.insert(0, part).insert(0, "ou=");
		}
		return AppContext.getSystemContext().loadObject(Template.class, getTemplateDn(templatePath));
	}
	
	private String getTemplateDn(String templatePath) {
		String parts[] = StringUtils.split(templatePath, "/");
		StringBuilder sb = new StringBuilder();
		sb.insert(0, getTemplateBaseDn());
		for (String part : parts) {
			sb.insert(0, ",");
			sb.insert(0, part).insert(0, "ou=");
		}
		return sb.toString();
	}


	private String getTemplateBaseDn() {
		return Config.getString(PROPERTY_BASE_DN);
	}


	private List<Template> loadTemplates(String templatePath) throws InvalidPrincipalException {
		return AppContext.getSystemContext().loadChildObjects(Template.class, getTemplateDn(templatePath), null);
	}


	private String getTemplatePath(Template template) {
		return template.getSlashPath(getTemplateBaseDn());
	}


	private void timeComboBoxChanged() {
		setPersonComboBoxValue((Person) this.personComboBox.getValue());
		try {
			initPersonData();
		} catch (NoValidPersonException | NoApplicationContextException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		initCustomerComboBox();
		initProjectComboBox();
		loadTimes();
		generate();
	}

	private void customerComboBoxChanged() {
		if (customerComboBox.getValue() != null) {
			projectComboBox.setValue(null);
		}
		try {
			initPersonData();
		} catch (NoValidPersonException | NoApplicationContextException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		initProjectComboBox();
		loadTimes();
		generate();
	}

	private void projectComboBoxChanged() {
		loadTimes();
		generate();
	}
	
	private void generate() {
		StreamResource pdfSource = createPDFStream();
		if (getPdfFileDownloader() != null) {
			downloadPdfButton.removeExtension(getPdfFileDownloader());
		}
		setPdfFileDownloader(new FileDownloader(pdfSource));
		getPdfFileDownloader().extend(downloadPdfButton);
		downloadPdfButton.setEnabled(true);
		downloadPdfButton.setCaption("Download PDF");

		StreamResource xlsSource = createXlsStream();
		if (getXlsFileDownloader() != null) {
			downloadXlsButton.removeExtension(getXlsFileDownloader());
		}
		setXlsFileDownloader(new FileDownloader(xlsSource));
		getXlsFileDownloader().extend(downloadXlsButton);
		downloadXlsButton.setEnabled(true);
		downloadXlsButton.setCaption("Download XLS");
		
	}

	private void loadTimes() {
		timeContainerDataSource.removeAllItems();
		try {
			PERIOD period = (PERIOD) timeComboBox.getValue();
			if (period != null) {
				timeContainerDataSource.addAll(getTimeWrappers(getPersonComboBoxValue(), period.getPeriod(), (Customer) customerComboBox.getValue(), (Project) projectComboBox.getValue(), READONLY.TRUE, 0));
			}
		} catch (IllegalStateException | IllegalArgumentException | TimeSelectException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		float total = TimeHelper.getHoursFromTimeWrapperList(timeContainerDataSource.getItemIds());
		hoursLabel.setValue(String.format("%.2f", total));
		daysLabel.setValue(String.format("%.2f", total/8.0));
	}

	private List<TimeWrapper> getReportData() {
		return timeContainerDataSource.getItemIds();
	}

	private List<Time> getTimes() {
		List<Time> times = new ArrayList<>();
		if (timeContainerDataSource.getItemIds() != null) {
			for (TimeWrapper timeWrapper : timeContainerDataSource.getItemIds()) {
				times.add(timeWrapper.getTime());
			}
		}
		return times;
	}


	private void initCustomerComboBox() {
	
		customerComboBox.setItems();
		customerComboBox.setItemCaptionGenerator(Customer::getName);
		if (customers != null) {
			customerComboBox.setItems(customers);
		}
	}

	private void initPersonData() throws NoValidPersonException, NoApplicationContextException {
		
		members = getMembers(getPersonComboBoxValue(), ((PERIOD) timeComboBox.getValue()).getPeriod());
		customers = getCustomers(members);
		projects = getProjects((Customer) customerComboBox.getValue(), members);
	}


	private void initProjectComboBox() {
	
		projectComboBox.setItems(projects);
		projectComboBox.setItemCaptionGenerator(Project::getName);
	}


	private StreamResource createPDFStream() {
		return new StreamResource(() ->
			{
//				String template = "reports/timeReport/TimeReport";
				if (reportComboBox.getValue() == null) {
					Notification.show("Bitte Report wählen", Type.ERROR_MESSAGE);
				}
				Template template = reportComboBox.getValue();

				TemplateEngine engine = TemplateEngine.getInstance(TYPE.JNDI);
				Map<String, Object> params = new HashMap<String, Object>();
				params.put("data", getReportData());
				params.put("times", getTimes());
				params.put("timeHelper", new TimeHelper());
				params.put("dataHelper", new DataHelper());
				params.put("today", DataHelper.getDisplayDay(new Date()));
				try {
//					return engine.executeTemplate(template + ".ftl", params, "UTF-8");
					return engine.executeTemplateAsPdf2(getTemplatePath(template) + ".ftl", params);
				} catch ( IOException | TemplateException | InvalidPrincipalException | ParserConfigurationException | SAXException | DocumentException  e) {
					LOG.error("Error generating Report", e);
				}
				return null;
			
		}, "TimeReport_" + DataHelper.getMilli(new Date()) + ".pdf");
	}


	private StreamResource createXlsStream() {
		return new StreamResource(() ->
			{
				if (reportComboBox.getValue() == null) {
					Notification.show("Bitte Report wählen", Type.ERROR_MESSAGE);
				}
				Template template = reportComboBox.getValue();

				Map<String, Object> params = new HashMap<String, Object>();
				params.put("data", getReportData());
				params.put("times", getTimes());
				params.put("timeHelper", new TimeHelper());
				params.put("dataHelper", new DataHelper());
				params.put("today", DataHelper.getDisplayDay(new Date()));
				try {
					return XlsDocuHelper.generate(TYPE.JNDI, getTemplatePath(template) + ".xls", params);
				} catch ( IOException | TemplateException | InvalidPrincipalException | ParserConfigurationException | SAXException | DocumentException  e) {
					LOG.error("Error generating Report", e);
				}
				return null;
			
		}, "TimeReport_" + DataHelper.getMilli(new Date()) + ".xls");
	}


	public FileDownloader getPdfFileDownloader() {
		return pdfFileDownloader;
	}


	public void setPdfFileDownloader(FileDownloader pdfFileDownloader) {
		this.pdfFileDownloader = pdfFileDownloader;
	}


	public Map<String, String> getConfiguration() {
		return configuration;
	}


	public void setConfiguration(Map<String, String> configuration) {
		this.configuration = configuration;
	}
	
	protected TEMPLATE_TYPE getTemplateType() {
		if (getConfiguration() != null) {
			for(TEMPLATE_TYPE type : TEMPLATE_TYPE.values()) {
				if (StringUtils.equals(type.name(), getConfiguration().get("type"))) {
					return type;
				}
			}
		}
		return TEMPLATE_TYPE.UNKNOWN;
	}
	
	protected String getTemplatePath() {
		if (getConfiguration() != null && getConfiguration().get("path") != null) {
			return getConfiguration().get("path");
		}
		return Config.getString("nicki.consulting.report.default", "reports/timeReport/TimeReport");
	}
	
	


	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		mainLayout.addComponent(verticalLayout_2);
		
		// summaryLayout
		summaryLayout = buildSummaryLayout();
		mainLayout.addComponent(summaryLayout);
		
		// timeTable
		timeTable = new Table();
		timeTable.setWidth("100%");
		timeTable.setHeight("100.0%");
		mainLayout.addComponent(timeTable);
		mainLayout.setExpandRatio(timeTable, 1.0f);
		
		return mainLayout;
	}


	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setWidth("-1px");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(true);
		verticalLayout_2.setSpacing(true);
		
		// filterLayout
		filterLayout = buildFilterLayout();
		verticalLayout_2.addComponent(filterLayout);
		
		// reportsLayout
		reportsLayout = buildReportsLayout();
		verticalLayout_2.addComponent(reportsLayout);
		
		return verticalLayout_2;
	}


	@AutoGenerated
	private HorizontalLayout buildFilterLayout() {
		// common part: create layout
		filterLayout = new HorizontalLayout();
		filterLayout.setWidth("-1px");
		filterLayout.setHeight("-1px");
		filterLayout.setMargin(false);
		filterLayout.setSpacing(true);
		
		// personComboBox
		personComboBox = new ComboBox();
		personComboBox.setCaption("Person");
		UIHelper.setImmediate(personComboBox, true);
		personComboBox.setWidth("-1px");
		personComboBox.setHeight("-1px");
		filterLayout.addComponent(personComboBox);
		
		// timeComboBox
		timeComboBox = new ComboBox();
		timeComboBox.setCaption("Zeitraum");
		UIHelper.setImmediate(timeComboBox, true);
		timeComboBox.setWidth("-1px");
		timeComboBox.setHeight("-1px");
		filterLayout.addComponent(timeComboBox);
		
		// customerComboBox
		customerComboBox = new ComboBox();
		customerComboBox.setCaption("Kunde");
		UIHelper.setImmediate(customerComboBox, true);
		customerComboBox.setWidth("-1px");
		customerComboBox.setHeight("-1px");
		filterLayout.addComponent(customerComboBox);
		
		// projectComboBox
		projectComboBox = new ComboBox();
		projectComboBox.setCaption("Projekt");
		UIHelper.setImmediate(projectComboBox, true);
		projectComboBox.setWidth("-1px");
		projectComboBox.setHeight("-1px");
		filterLayout.addComponent(projectComboBox);
		
		return filterLayout;
	}


	@AutoGenerated
	private HorizontalLayout buildReportsLayout() {
		// common part: create layout
		reportsLayout = new HorizontalLayout();
		reportsLayout.setWidth("-1px");
		reportsLayout.setHeight("-1px");
		reportsLayout.setMargin(false);
		reportsLayout.setSpacing(true);
		
		// reportComboBox
		reportComboBox = new ComboBox();
		reportComboBox.setCaption("Report");
		UIHelper.setImmediate(reportComboBox, true);
		reportComboBox.setWidth("-1px");
		reportComboBox.setHeight("-1px");
		reportsLayout.addComponent(reportComboBox);
		
		// downloadPdfButton
		downloadPdfButton = new Button();
		downloadPdfButton.setCaption("PDF");
		UIHelper.setImmediate(downloadPdfButton, true);
		downloadPdfButton.setWidth("-1px");
		downloadPdfButton.setHeight("-1px");
		reportsLayout.addComponent(downloadPdfButton);
		reportsLayout.setComponentAlignment(downloadPdfButton, new Alignment(9));
		
		// downloadXlsButton
		downloadXlsButton = new Button();
		downloadXlsButton.setCaption("Excel");
		UIHelper.setImmediate(downloadXlsButton, true);
		downloadXlsButton.setWidth("-1px");
		downloadXlsButton.setHeight("-1px");
		reportsLayout.addComponent(downloadXlsButton);
		reportsLayout.setComponentAlignment(downloadXlsButton, new Alignment(9));
		
		return reportsLayout;
	}


	@AutoGenerated
	private HorizontalLayout buildSummaryLayout() {
		// common part: create layout
		summaryLayout = new HorizontalLayout();
		summaryLayout.setWidth("-1px");
		summaryLayout.setHeight("-1px");
		summaryLayout.setMargin(true);
		summaryLayout.setSpacing(true);
		
		// hoursLabel
		hoursLabel = new Label();
		hoursLabel.setCaption("Summe (h)");
		hoursLabel.setWidth("-1px");
		hoursLabel.setHeight("-1px");
		hoursLabel.setValue("0");
		summaryLayout.addComponent(hoursLabel);
		
		// daysLabel
		daysLabel = new Label();
		daysLabel.setCaption("Summe (Tage)");
		daysLabel.setWidth("-1px");
		daysLabel.setHeight("-1px");
		daysLabel.setValue("Label");
		summaryLayout.addComponent(daysLabel);
		
		return summaryLayout;
	}


	public FileDownloader getXlsFileDownloader() {
		return xlsFileDownloader;
	}


	public void setXlsFileDownloader(FileDownloader xlsFileDownloader) {
		this.xlsFileDownloader = xlsFileDownloader;
	}

}
