package org.mgnl.nicki.consulting.views;

import java.io.IOException;
import java.io.InputStream;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.parsers.ParserConfigurationException;

import org.mgnl.nicki.consulting.core.helper.TimeHelper;
import org.mgnl.nicki.consulting.core.model.Customer;
import org.mgnl.nicki.consulting.core.model.Member;
import org.mgnl.nicki.consulting.core.model.Project;
import org.mgnl.nicki.consulting.data.BeanContainerDataSource;
import org.mgnl.nicki.consulting.data.TimeWrapper;
import org.mgnl.nicki.consulting.db.TimeSelectException;
import org.mgnl.nicki.core.auth.InvalidPrincipalException;
import org.mgnl.nicki.core.helper.DataHelper;
import org.mgnl.nicki.template.engine.ConfigurationFactory.TYPE;
import org.mgnl.nicki.template.engine.TemplateEngine;
import org.mgnl.nicki.vaadin.base.menu.application.View;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.xml.sax.SAXException;

import com.itextpdf.text.DocumentException;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.FileDownloader;
import com.vaadin.server.StreamResource;
import com.vaadin.server.StreamResource.StreamSource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

import freemarker.template.TemplateException;

public class ReportsView extends BaseView implements View  {
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Table timeTable;
	@AutoGenerated
	private HorizontalLayout summaryLayout;
	@AutoGenerated
	private Label totalLabel;
	@AutoGenerated
	private HorizontalLayout filterLayout;
	@AutoGenerated
	private Button downloadButton;
	@AutoGenerated
	private ComboBox projectComboBox;
	@AutoGenerated
	private ComboBox customerComboBox;
	@AutoGenerated
	private ComboBox timeComboBox;


	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	private static final long serialVersionUID = -2330776406366438437L;
	private static final Logger LOG = LoggerFactory.getLogger(ReportsView.class);
	private boolean isInit;

	private FileDownloader pdfFileDownloader;
	
	private Collection<Member> members;
	
	private Collection<Customer> customers;
	
	private Collection<Project> projects;
	private BeanContainerDataSource<TimeWrapper> timeContainerDataSource;
	
	public ReportsView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}


	@Override
	public void init() {
		try {
			initPersonData();
		} catch (NoValidPersonException | NoApplicationContextException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		if (!isInit) {

			initTimeComboBox(this.timeComboBox);
			customerComboBox.setEnabled(true);
			projectComboBox.setEnabled(true);

			downloadButton.setEnabled(false);
			
			timeContainerDataSource = new BeanContainerDataSource<>(TimeWrapper.class);
			timeTable.setContainerDataSource(timeContainerDataSource);
			timeTable.setVisibleColumns("member", "day", "start", "end", "pause", "text");
			timeTable.setColumnHeaders("Projekt", "Datum", "von", "bis", "Pause", "Tätigkeit");
			
			timeComboBox.addValueChangeListener(event -> {timeComboBoxChanged();});
			customerComboBox.addValueChangeListener(event -> {customerComboBoxChanged();});
			projectComboBox.addValueChangeListener(event -> {projectComboBoxChanged();});
			timeComboBoxChanged();
		}
		initCustomerComboBox();
		initProjectComboBox();
		loadTimes();
	}

	private void timeComboBoxChanged() {
		loadTimes();
		generate();
	}

	private void customerComboBoxChanged() {
		if (customerComboBox.getValue() != null) {
			projectComboBox.setValue(null);
		}
		loadTimes();
		generate();
	}

	private void projectComboBoxChanged() {
		if (projectComboBox.getValue() != null) {
			customerComboBox.setValue(null);
		}
		loadTimes();
		generate();
	}
	
	private void generate() {
		StreamResource pdfSource = createPDFStream();
		if (getPdfFileDownloader() != null) {
			downloadButton.removeExtension(getPdfFileDownloader());
		}
		setPdfFileDownloader(new FileDownloader(pdfSource));
		getPdfFileDownloader().extend(downloadButton);
		downloadButton.setEnabled(true);
		downloadButton.setCaption("Download");
		
	}

	private void loadTimes() {
		timeContainerDataSource.removeAllItems();
		try {
			timeContainerDataSource.addAll(getTimeWrappers(getPerson(), (PERIOD) timeComboBox.getValue(), (Customer) customerComboBox.getValue(), (Project) projectComboBox.getValue(), READONLY.TRUE, 0));
		} catch (IllegalStateException | IllegalArgumentException | TimeSelectException | NoValidPersonException
				| NoApplicationContextException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		float total = TimeHelper.getHoursFromTimeWrapperList(timeContainerDataSource.getItemIds());
		totalLabel.setValue(String.format("%.2f", total));
	}

	private List<TimeWrapper> getReportData() {
		return timeContainerDataSource.getItemIds();
//		try {
//			return getTimes(getPerson(), (PERIOD) timeComboBox.getValue(), (Customer) customerComboBox.getValue(), (Project) projectComboBox.getValue());
//		} catch (TimeSelectException | NoValidPersonException | NoApplicationContextException e) {
//			LOG.error("Error reading time");
//		}
//		return new ArrayList<>();
	}


	private void initCustomerComboBox() {
	
		customerComboBox.removeAllItems();
		if (customers != null) {
			for (Customer customer : customers) {
				customerComboBox.addItem(customer);
				customerComboBox.setItemCaption(customer, customer.getName());
			}
		}
	}

	private void initPersonData() throws NoValidPersonException, NoApplicationContextException {
		
		if (members == null) {
			members = getMembers(getPerson());
		}
		
		if (customers == null) {
			customers = getCustomers(members);
		}
		
		if (projects == null) {
			projects = getProjects(members);
		}
	}


	private void initProjectComboBox() {
	
		projectComboBox.removeAllItems();
		for (Project project: projects) {
			projectComboBox.addItem(project);
			projectComboBox.setItemCaption(project, project.getName());
		}
	}


	private StreamResource createPDFStream() {
		return new StreamResource(new StreamSource() {
			private static final long serialVersionUID = 1L;

			@Override
			public InputStream getStream() {
				String template = "reports/timeReport/TimeReport";

				TemplateEngine engine = TemplateEngine.getInstance(TYPE.JNDI);
				Map<String, Object> params = new HashMap<String, Object>();
				params.put("data", getReportData());
				params.put("timeHelper", new TimeHelper());
				params.put("dataHelper", new DataHelper());
				params.put("today", DataHelper.getDisplayDay(new Date()));
				try {
//					return engine.executeTemplate(template + ".ftl", params, "UTF-8");
					return engine.executeTemplateAsPdf2(template + ".ftl", params);
				} catch ( IOException | TemplateException | InvalidPrincipalException | ParserConfigurationException | SAXException | DocumentException  e) {
					LOG.error("Error generating WLAN Ticket", e);
				}
				return null;
			}
		}, "TimeReport_" + DataHelper.getMilli(new Date()) + ".pdf");
	}


	public FileDownloader getPdfFileDownloader() {
		return pdfFileDownloader;
	}


	public void setPdfFileDownloader(FileDownloader pdfFileDownloader) {
		this.pdfFileDownloader = pdfFileDownloader;
	}


	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// filterLayout
		filterLayout = buildFilterLayout();
		mainLayout.addComponent(filterLayout);
		
		// summaryLayout
		summaryLayout = buildSummaryLayout();
		mainLayout.addComponent(summaryLayout);
		
		// timeTable
		timeTable = new Table();
		timeTable.setImmediate(false);
		timeTable.setWidth("-1px");
		timeTable.setHeight("100.0%");
		mainLayout.addComponent(timeTable);
		mainLayout.setExpandRatio(timeTable, 1.0f);
		
		return mainLayout;
	}


	@AutoGenerated
	private HorizontalLayout buildFilterLayout() {
		// common part: create layout
		filterLayout = new HorizontalLayout();
		filterLayout.setImmediate(false);
		filterLayout.setWidth("-1px");
		filterLayout.setHeight("-1px");
		filterLayout.setMargin(true);
		filterLayout.setSpacing(true);
		
		// timeComboBox
		timeComboBox = new ComboBox();
		timeComboBox.setCaption("Zeitraum");
		timeComboBox.setImmediate(true);
		timeComboBox.setWidth("-1px");
		timeComboBox.setHeight("-1px");
		filterLayout.addComponent(timeComboBox);
		
		// customerComboBox
		customerComboBox = new ComboBox();
		customerComboBox.setCaption("Kunde");
		customerComboBox.setImmediate(true);
		customerComboBox.setWidth("-1px");
		customerComboBox.setHeight("-1px");
		filterLayout.addComponent(customerComboBox);
		
		// projectComboBox
		projectComboBox = new ComboBox();
		projectComboBox.setCaption("Projekt");
		projectComboBox.setImmediate(true);
		projectComboBox.setWidth("-1px");
		projectComboBox.setHeight("-1px");
		filterLayout.addComponent(projectComboBox);
		
		// downloadButton
		downloadButton = new Button();
		downloadButton.setCaption("Download");
		downloadButton.setImmediate(true);
		downloadButton.setWidth("-1px");
		downloadButton.setHeight("-1px");
		filterLayout.addComponent(downloadButton);
		filterLayout.setComponentAlignment(downloadButton, new Alignment(9));
		
		return filterLayout;
	}


	@AutoGenerated
	private HorizontalLayout buildSummaryLayout() {
		// common part: create layout
		summaryLayout = new HorizontalLayout();
		summaryLayout.setImmediate(false);
		summaryLayout.setWidth("-1px");
		summaryLayout.setHeight("-1px");
		summaryLayout.setMargin(true);
		summaryLayout.setSpacing(true);
		
		// totalLabel
		totalLabel = new Label();
		totalLabel.setCaption("Summe (h)");
		totalLabel.setImmediate(false);
		totalLabel.setWidth("-1px");
		totalLabel.setHeight("-1px");
		totalLabel.setValue("0");
		summaryLayout.addComponent(totalLabel);
		
		return summaryLayout;
	}

}
