package org.mgnl.nicki.consulting.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

public class SaveOrIgnoreDialog extends CustomComponent {
	private static final long serialVersionUID = 3551076231334629551L;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout buttonsLayout;
	@AutoGenerated
	private Button ignoreButton;
	@AutoGenerated
	private Button saveButton;
	@AutoGenerated
	private Label introLabel;
	
	public enum DECISION {SAVE, IGNORE};

	public SaveOrIgnoreDialog(SaveOrIgnoreHandler handler) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		saveButton.addClickListener(event -> {handler.handle(DECISION.SAVE);});
		ignoreButton.addClickListener(event -> {handler.handle(DECISION.IGNORE);});
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// introLabel
		introLabel = new Label();
		introLabel.setImmediate(false);
		introLabel.setWidth("-1px");
		introLabel.setHeight("-1px");
		introLabel.setValue("Die Daten wurden verändert");
		mainLayout.addComponent(introLabel);
		
		// horizontalLayout_1
		buttonsLayout = buildHorizontalLayout_1();
		mainLayout.addComponent(buttonsLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		buttonsLayout = new HorizontalLayout();
		buttonsLayout.setImmediate(false);
		buttonsLayout.setWidth("-1px");
		buttonsLayout.setHeight("-1px");
		buttonsLayout.setMargin(false);
		buttonsLayout.setSpacing(true);
		
		// saveButton
		saveButton = new Button();
		saveButton.setCaption("Speichern");
		saveButton.setImmediate(false);
		saveButton.setWidth("-1px");
		saveButton.setHeight("-1px");
		buttonsLayout.addComponent(saveButton);
		
		// ignoreButton
		ignoreButton = new Button();
		ignoreButton.setCaption("Verwerfen");
		ignoreButton.setImmediate(false);
		ignoreButton.setWidth("-1px");
		ignoreButton.setHeight("-1px");
		buttonsLayout.addComponent(ignoreButton);
		
		return buttonsLayout;
	}
	
}
