DROP TABLE SURVEYCONFIG;

DROP TABLE SURVEYTOPICS;

DROP TABLE SURVEYTOPICVALUES;

DROP TABLE SURVEYVOTES;

DROP TABLE SURVEYNOTIFY;

CREATE TABLE SURVEYCONFIG (
  ID bigint NOT NULL AUTO_INCREMENT,
  NAME varchar(1000) NOT NULL,
  DESCRIPTION varchar(1000) NOT NULL,
  OWNER varchar(1000) NOT NULL,
  START_TIME timestamp,
  END_TIME timestamp,
  VISIBLE_TIME timestamp,
  ADD_TOPIC int,
  ADD_COMMENT int,
  CONSTRAINT SURVEYCONFIG_PK PRIMARY KEY (ID)
);

CREATE TABLE SURVEYTOPICS (
  ID bigint NOT NULL AUTO_INCREMENT,
  SURVEY_ID bigint NOT NULL,
  NAME varchar(1000) NOT NULL,
  DESCRIPTION varchar(1000) NOT NULL,
  OWNER varchar(1000) NOT NULL,
  CONSTRAINT SURVEYTOPICS_PK PRIMARY KEY (ID)
);

CREATE TABLE SURVEYTOPICVALUES (
  ID bigint NOT NULL AUTO_INCREMENT,
  TOPIC_ID bigint NOT NULL,
  NAME varchar(1000) NOT NULL,
  DESCRIPTION varchar(1000) NOT NULL,
  WEIGHT int NOT NULL,
  CONSTRAINT SURVEYTOPICVALUES_PK PRIMARY KEY (ID)
);

CREATE TABLE SURVEYVOTES (
  ID bigint NOT NULL AUTO_INCREMENT,
  SURVEYTOPICVALUE_ID bigint NOT NULL,
  USER_ID varchar(1000) NOT NULL,
  COMMENT varchar(1000) NOT NULL,
  CONSTRAINT SURVEYVOTES_PK PRIMARY KEY (ID)
);

CREATE TABLE SURVEYNOTIFY (
  ID bigint NOT NULL AUTO_INCREMENT,
  SURVEY_ID bigint NOT NULL,
  USER_ID varchar(1000) NOT NULL,
  CONSTRAINT SURVEYNOTIFY_PK PRIMARY KEY (ID)
);