DROP TABLE APP.TIME;

CREATE TABLE APP.TIME (
  ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  MEMBER_ID bigint NOT NULL,
  TEXT varchar(1000) NOT NULL,
  START_TIME timestamp,
  END_TIME timestamp,
  PAUSE int,
  HOURS float not null,
  CONSTRAINT TIME_PK PRIMARY KEY (ID)
);