DROP TABLE APP.PROJECTS;

CREATE TABLE APP.PROJECTS (
  ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  CUSTOMER_ID bigint NOT NULL,
  NAME varchar(1000) NOT NULL,
  CUSTOMER_REFERENCE varchar(1000) NOT NULL,
  CONTACT varchar(1000) NOT NULL,
  PHONE varchar(1000),
  EMAIL varchar(1000),
  DAYS int,
  RATE float,
  ACTIVE int,
  START_DATE date,
  END_DATE date,
  CONSTRAINT PROJECTS_PK PRIMARY KEY (ID)
);
