DROP TABLE APP.MEMBERS;

CREATE TABLE APP.MEMBERS (
  ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  PROJECT_ID bigint NOT NULL,
  PERSON_ID bigint NOT NULL,
  ROLE varchar(1000),
  DAYS int,
  RATE float,
  ACTIVE int,
  START_DATE date,
  END_DATE date,
  CONSTRAINT MEMBERS_PK PRIMARY KEY (ID)
);