DROP TABLE MEMBERS;

CREATE TABLE MEMBERS (
  ID bigint NOT NULL AUTO_INCREMENT,
  PROJECT_ID bigint NOT NULL,
  PERSON_ID bigint NOT NULL,
  ROLE varchar(1000),
  DAYS int,
  RATE float,
  ACTIVE int,
  START_DATE date,
  END_DATE date,
  CONSTRAINT MEMBERS_PK PRIMARY KEY (ID)
);