DROP TABLE APP.SURVEYCONFIG;

DROP TABLE APP.SURVEYTOPICS;

DROP TABLE APP.SURVEYCHOICES;

DROP TABLE APP.SURVEYVOTES;

DROP TABLE APP.SURVEYNOTIFY;

CREATE TABLE APP.SURVEYCONFIG (
  ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  NAME varchar(1000) NOT NULL,
  DESCRIPTION varchar(1000) NOT NULL,
  OWNER varchar(1000) NOT NULL,
  START_TIME timestamp,
  END_TIME timestamp,
  VISIBLE_TIME timestamp,
  ADD_TOPIC int,
  ADD_COMMENT int,
  CONSTRAINT SURVEYCONFIG_PK PRIMARY KEY (ID)
);

CREATE TABLE APP.SURVEYTOPICS (
  ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  SURVEY_ID bigint NOT NULL,
  NAME varchar(1000) NOT NULL,
  DESCRIPTION varchar(1000) NOT NULL,
  OWNER varchar(1000) NOT NULL,
  CONSTRAINT SURVEYTOPICS_PK PRIMARY KEY (ID)
);

CREATE TABLE APP.SURVEYCHOICES (
  ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  SURVEY_ID bigint NOT NULL,
  NAME varchar(1000) NOT NULL,
  DESCRIPTION varchar(1000) NOT NULL,
  WEIGHT int NOT NULL,
  CONSTRAINT SURVEYCHOICES_PK PRIMARY KEY (ID)
);

CREATE TABLE APP.SURVEYVOTES (
  ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  SURVEYTOPIC_ID bigint NOT NULL,
  SURVEYCHOICE_ID bigint,
  USER_ID varchar(1000) NOT NULL,
  COMMENT varchar(1000),
  CONSTRAINT SURVEYVOTES_PK PRIMARY KEY (ID)
);

CREATE TABLE APP.SURVEYNOTIFY (
  ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  SURVEY_ID bigint NOT NULL,
  USER_ID varchar(1000) NOT NULL,
  MODIFIED timestamp,
  CONSTRAINT SURVEYNOTIFY_PK PRIMARY KEY (ID)
);