DROP TABLE FORECAST_STAGES;

CREATE TABLE FORECAST_STAGES (
  ID bigint NOT NULL AUTO_INCREMENT,
  NAME varchar(1000),
  MIN_PROB int,
  MAX_PROB int,
  POSITION int,
  CONSTRAINT FORECAST_STAGES_PK PRIMARY KEY (ID)
);